name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          working-directory: "myblog"

      - name: Build Hugo App
        run: hugo --minify

      - name: CDK Diff
        uses: youyo/aws-cdk-github-actions@v2.1.1
        with:
          cdk_subcommand: diff
          working_dir: infra
