name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13

      - name: Build Hugo App
        run: hugo --minify
        working-directory: myblog

      - name: CDK Diff
        uses: youyo/aws-cdk-github-actions@v2.1.1
        working-directory: infra
        run: cdk diff BlogInfraStack
